module.exports = {
    SP_DISABLE_LOGS: 'true',
    SP_PRETTY_PRINT: 'true',
    STATE_DEFAULT: 'DEFAULT',
    STATE_INFO: 'INFO',
    STATE_WARN: 'WARN',
    STATE_ERROR: 'ERROR',
    STATE_DEBUG: 'DEBUG',
    STATE_TRACE: 'TRACE',
    STATE_FATAL: 'FATAL',
}